### ISSUE TITLE
Badges: browsers, file size, others?

### ISSUE THREAD

**Issue by exogen** [walmartlabs/little-loader#25]
My project for generating prettier Sauce Labs badges is up at [exogen/badge-matrix](https://github.com/exogen/badge-matrix). It's currently running on a Heroku dyno that doesn't need to sleep, at `badges.herokuapp.com`. Here's a badge for `little-loader`:

![little-loader Browser Support](http://badges.herokuapp.com/sauce/wml-little-loader)

Should be easy to host anywhere if you don't like Heroku. (For reference, on my connection Sauce Labs' badge has avg response time of 0.41s and the image is 28K; badge-matrix on my hobby Heroku dyno has avg response time of 0.6s and the image is 2.4K, not too terrible. The time is dwarfed by potentially needing to talk to the APIs anyway, no matter where hosted.)

I also happened across [ngryman/badge-size](https://github.com/ngryman/badge-size) which can generate a file size badge for any file in your repo. I think that's cool because it's something we're emphasizing, and we currently need to update it in the README every time it changes.

We don't have any dist files in our repo to point it at yet, but here's a size badge for the source file (it can tell you the gzip size too):

![little-loader size](https://badge-size.herokuapp.com/walmartlabs/little-loader/master/lib/little-loader.js.svg)

**Comment by ryan-roemer** [comment]
@exogen -- We _do_ upload `dist` builds to CDN. E.g., https://npmcdn.com/little-loader@0.1.0/dist/little-loader.min.js

Feel free to open a PR with new badge awesomeness!
