### ISSUE TITLE
Optimize source for mingzipped size.

### ISSUE THREAD

**Issue by pygy** [walmartlabs/little-loader#29]
I was contemplating refactoring little-loader a bit to try to make it even smaller (I kinda like that kind of challenge, no golf, promised), then I realized that what I was aiming for (smallest mingzipped size) may not be what you're aiming for...

So, if conflict arises, what do you prefer? A smaller minified build or a smaller mingzipped build?

**Comment by ryan-roemer** [comment]
Ah, `mingzipped` is actually favored, and some of the micro-optimizations we have in there might be better unwound for gzip's sake (e.g., https://github.com/walmartlabs/little-loader/blob/master/lib/little-loader.js#L22-L27)

Feel free to open a PR with results and make sure to pass all the tests :wink:  (And there may be some issues with PR verifying of forks for sauce credentials, so perhaps local validate with windows?)

**Comment by pygy** [comment]
L22-L27, that's what I had in mind.

That and _createFinish, which is AFAICT not needed, you can bind the inner function to `_finihsh` directly, and define `finishCB` (renamed `_cleanup`) where you currently run `_createFinish`.

I have old netbooks running XP + IE8, I'll try to give it a crack.

**Comment by ryan-roemer** [comment]
Fixed in #32 (we'll take up the `head` removal idea in a separate ticket)
