### ISSUE TITLE
The test suite fails on OS X 10.10

### ISSUE THREAD

**Issue by pygy** [walmartlabs/little-loader#30]
The `fs-events` package refuses to install, and the test runner (`npm run check`) crashes  with

```
[SERVER] [error] Error: Missing /Users/pygy/src/little-loader/node_modules/selenium-standalone/.selenium/chromedriver/2.18-x64-chromedriver
  1) "before all" hook
```

Here's [the full log](https://gist.github.com/pygy/9efa5470bcfb38ba28a1), including early successes then a crash.

This is on the master branch, freshly cloned.

```
~/s/little-loader git:master ❯❯❯ node -v
v5.1.1
~/s/little-loader git:master ❯❯❯ npm -v
3.5.2
```

**Comment by ryan-roemer** [comment]
It looks like you don't have chromedriver installed... Did you do both install steps in: https://github.com/walmartlabs/little-loader#development

```
$ npm install
$ npm run install-dev
```

and did `install-dev` succeed?

`fs-events` has had some bumps. Maybe check a new rev?

**Comment by pygy** [comment]
Oh, no, sorry, my bad. Now I get `Error: Another Selenium process is already running`, and a prompt to install the latest JRE. Proceeding... I had it installed, but reinstalled the latest version to be sure... no dice :-/

I've updated the gist above with the new log.

**Comment by ryan-roemer** [comment]
For `Error: Another Selenium process is already running` just `ps | grep -i selenium` and kill stuff.

I think you can ignore the JRE thing.

(This is the unfortunate scenario where Selenium, despite all its warts, is still the best functional test tool for driving browsers, so we bow down to our Java gods :wink: )

**Comment by pygy** [comment]
No selenium in sight in the `ps` output (I had already checked).

**Comment by ryan-roemer** [comment]
Hmm... Look for `java`?

**Comment by pygy** [comment]
Neither. Off to bed now, I'll check again tomorrow.
