### ISSUE TITLE
_addScript throws if there is no other script in the <head>

### ISSUE THREAD

**Issue by znation** [walmartlabs/little-loader#37]
On a page with no script tags in the `<head>` (only in `<body>`) the loader appears to throw exceptions in `_addScript` (for any script load requested).

The call stack looks like:
```
little-loader.js:43 Uncaught TypeError: Cannot read property 'parentNode' of undefined

_addScript	@	little-loader.js:43
_lload	@	little-loader.js:209
// my code below that
```

The cause seems to be the assumption of the existence of at least one script tag in `<head>` [here](https://github.com/walmartlabs/little-loader/blob/master/lib/little-loader.js#L40):
```javascript
var firstScript = document.getElementsByTagName("script")[0];

// Append the script to the DOM, triggering execution.
firstScript.parentNode.insertBefore(script, firstScript);
```

**Comment by ryan-roemer** [comment]
@znation -- Can you walk me through a situation / link to a raw HTML gist that would have little-loader loaded on a page some how and _not_ have a `script` tag?

@exogen -- Can you brainstorm the tightest way to handle no `script` tags for us?

Thanks!!!

**Comment by znation** [comment]
@ryan-roemer Interesting, the repro is not quite what I thought. I put together a simple page with two script tags in `<body>` (and nothing in `<head>`) and can't repro it (my initial assumption about body vs. head was wrong). I will keep trying to get a minimal repro and when I have narrowed it down I'll modify the title of the issue. Thanks!

**Comment by exogen** [comment]
Interested to see what the final repro will be – as you've found, it makes no assumption about where the `script` will be, and can be used with only `<body>` scripts.

@znation: Is there a chance you're using this in conjunction with some other dynamic script loader? I've seen some libraries *remove* `<script>` elements from the document (presumably they've been executed and thus no longer need to be around?). Or possibly some kind of noscript browser extension?

As for handling this case: I'm thinking if there is no `<script>` found, we can just append it to the end of `<body>`. Honestly I'm not sure why our current approach is even so widespread among script loaders – maybe it just conveniently keeps all the scripts together for easier inspection?

**Comment by znation** [comment]
@exogen @ryan-roemer I don't have a minimal repro yet but I suspect it's my environment. I'm using a bunch of Webpack and React hot-loading stuff that is messing with script loading -- and somehow `document.getElementsByTagName('script')` is returning an empty array in this case, even with a very similar codepath to my attempted repro. Even with only one script tag on the page, the one both including and calling `little-loader`, I can't repro it, and like you said -- running script without a script tag at all seems like a virtual impossibility (and isn't the case I'm in). Feel free to close this issue if nobody else seems affected; I'm sure I can work around it by making my script-loading environment a bit less weird.

**Comment by znation** [comment]
And sorry for jumping to conclusions; the root cause here doesn't appear to be a bug in this library.

**Comment by ryan-roemer** [comment]
@znation -- We'll close for now and reopen if you or anyone else can get us a reproduction. Thanks!
