### ISSUE TITLE
Sauce Labs no more?

### ISSUE THREAD

**Issue by pygy** [walmartlabs/little-loader#38]
Howdy :-)

The [Sauce Labs page for little-loader](https://saucelabs.com/u/wml-little-loader) is empty, which causes a grey "unknown badge" in the readme.

Since @exogen's [badge-matrix](https://github.com/exogen/badge-matrix) uses this project as an example, its readme is broken as well.

**Comment by ryan-roemer** [comment]
I think Sauce Labs cleared out results for all their free accounts (or something) somewhat recently. I've kicked travis to rebuild `master` to make sure the whole thing works and hopefully the badge updates too.

**Comment by ryan-roemer** [comment]
That worked. We're back with the full badge now. Thanks for the note @pygy
