### ISSUE TITLE
Support crossorigin="anonymous" 

### ISSUE THREAD

**Issue by jknight12882** [walmartlabs/little-loader#48]
Scripts loaded using `little-loader` can't be debugged using `window.onerror` because of CORS (you just get the standard 'Script error.' error). It would be nice to be able to set the `crossorigin` policy on the `<script />` tag so that we can debug scripts that are hosted on a third party domain (such as a CDN)

**Comment by ryan-roemer** [comment]
Supported via generic `setup(script)` callback.
