### ISSUE TITLE
Adding a Custom data-* attr when loading script

### ISSUE THREAD

**Issue by tfuqua** [walmartlabs/little-loader#59]
Is there a way to specify a customer attribute (https://html.spec.whatwg.org/multipage/dom.html#embedding-custom-non-visible-data-with-the-data-%2a-attributes) when loading scripts with little-loader?

Thanks!

**Comment by exogen** [comment]
Hi @tfuqua! You should be able to accomplish this with the [setup](https://github.com/walmartlabs/little-loader#calling) option, which receives the `<script>` node before injection.

like:

```js
setup(script) {
  script.dataset.foo = 'value';
}
```

or:

```js
setup(script) {
  script.setAttribute('data-foo', 'value');
}
```

(those should be equivalent)

**Comment by tfuqua** [comment]
I'll give that a try, thank you so much for the quick response!

**Comment by tfuqua** [comment]
Issue resolved with help from @exogen above
